---
# PRIMO PLAY: Setup disco dedicato per Rancher su tutti i server
- hosts: all
  become: yes
  gather_facts: yes
  roles:
    - role: create_disk

# SECONDO PLAY: Aggiorna /etc/hosts su tutti i server
- hosts: all,local
  become: yes
  gather_facts: no
  roles:
    - role: update_hosts_file

# TERZO PLAY: Installazione Rancher su TUTTI i masters
- hosts: masters
  become: yes
  gather_facts: no
  roles:
    - role: master1_install
    - role: master1_config
    - role: master1_kubectl
    - role: master1_helm_cert_manager_install

# QUARTO PLAY: Creazione cluster RKE2 su TUTTI i masters
- hosts: masters
  become: yes
  gather_facts: no
  roles:
    - role: master1_create_cluster

# QUINTO PLAY: Setup kubectl sui nuovi manager
- hosts: new_managers
  become: yes
  gather_facts: no
  roles:
    - kubectl_setup
