---

- name: Installing nfs-utils 
  dnf:
    name: 
      - nfs-utils
    state: present

- name: Creating directory
  file:
    state: directory
    owner: nobody
    group: nobody
    path: "{{ item }}"
  loop:
    - "{{ export_dir }}/{{ backup_dir }}"
    - "{{ export_dir }}/{{ k8s_dir }}"

- name: Adding export to the file
  blockinfile:
    path: /etc/exports
    block: |
      {% for dir in export_dirs %}
      {{ dir }}{% for client in nfs_clients %} {{ client }}(rw,sync,no_subtree_check){% endfor %}
      
      {% endfor %}
    create: yes
  vars:
    export_dirs:
      - "{{ export_dir }}/{{ backup_dir }}"
      - "{{ export_dir }}/{{ k8s_dir }}"
  notify: export fs
